stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
  - apt-get update -qq && apt-get install -y -qq sqlite3 libsqlite3-dev nodejs
  - bundle install --path /cache
  - bundle exec rake db:create RAILS_ENV=test
  - bundle exec rake test
  - bundle exec rspec
  - bundle exec rubocop

build:
  stage: build
  script:
  - ./scripts/build_image.sh $CI_COMMIT_REF_SLUG $CI_COMMIT_REF_NAME $CI_COMMIT_REF_NAME

development:
  stage: deploy
  script:
  - echo 'Delopying for development is not enabled'

staging:
  stage: deploy
  script:
  - echo 'Delopying for staging is not enabled'
  only:
  - master

production:
  stage: deploy
  script:
  - echo 'Delopying for production is not enabled'
  only:
  - tags
